export const SET_EMPLOYERID='SET_EMPLOYERID'
export const SET_INTERNID='SET_INTERNID'
export const LOGOUT='LOGOUT';
export const SET_SEARCH='SET_SEARCH'
export const SET_FILTER_JOBS='SET_FILTER_JOBS'
export const SET_JOBS='SET_JOBS'
export const SET_JOB='SET_JOB'
export const SEARCH_OFF='SEARCH_OFF'
export const SET_MCQ_ANSWER='SET_MCQ_ANSWER'
export const SET_MQC_STATUS='SET_MQC_STATUS'
export const RESET_MCQ="RESET_MCQ"
export const SET_MCQ="SET_MCQ"
export const SET_MEDAL="SET_MEDAL"
export const SET_GPLAYED = "SET_GPLAYED"